# Используем базовый образ Python
FROM python:3.12-slim

# Устанавливаем зависимости
RUN pip install python-telegram-bot

# Копируем файлы проекта в контейнер
COPY . /app

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем переменные окружения
ENV BOT_TOKEN=$BOT_TOKEN

# Запускаем бота
CMD ["python", "svn-task-manager-bot.py"]